version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - ./db:/chroma/chroma  # 벡터 데이터베이스 영구 저장
    environment:
      - ALLOW_RESET=True
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]  # JSON 배열 형식으로 변경
    ports:
      - "8000:8000"  # 호스트:컨테이너
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  rag-network:
    driver: bridge
